[package]
name = "crates-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ctoml"
path = "src/main.rs"

[dependencies]
toml = { workspace = true }
bumpalo = { workspace = true }
unicode-width = "0.1.11"
