[package]
name = "crates_nvim"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.7.2", features = ["luajit", "module", "vendored", "serialize"] }
serde = { version = "1.0", features = ["serde_derive"] }
serde_derive = "1.0"
