[workspace]
resolver = "2"
members = [
    "crates-nvim",
    "crates-toml",
    "crates-cli",
    "crates-semver",
]

[workspace.dependencies]
toml = { package = "crates-toml", path = "crates-toml" }
bumpalo = { version = "3.15.4", features = ["collections"] }

[profile.release]
strip = true
