[workspace]
resolver = "2"
members = [
    "crates-nvim",
    "crates-toml",
    "crates-cli",
    "crates-semver",
    "crates-common",
    "fuzz",
]

[workspace.dependencies]
toml = { package = "crates-toml", path = "crates-toml" }
common = { package = "crates-common", path = "crates-common" }
semver = { package = "crates-semver", path = "crates-semver" }
bumpalo = { version = "3.15.4", features = ["collections"] }

[profile.release]
strip = true
