[package]
name = "dingey-toml"
version = "0.1.0"
edition = "2024"

[features]
default = []
serde = ["dep:serde"]

[dependencies]
common = { workspace = true }
bumpalo = { workspace = true }
indexmap = { workspace = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
toml-test-harness = "0.4.12"
toml-test-data = "1.13.1"
libtest-mimic = "0.8.1"

[[test]]
name = "valid"
harness = false

[[test]]
name = "invalid"
harness = false
