[package]
name = "dingey-toml"
version = "0.1.0"
edition = "2024"

[features]
default = ["serde"]
serde = ["dep:serde"]

[dependencies]
common = { workspace = true }
bumpalo = { workspace = true }
indexmap = { workspace = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
toml-test-harness = "1.4.0"
toml-test-data = "2.4.0"
libtest-mimic = "0.8.1"
walkdir = "2.5.0"

[[test]]
name = "valid"
harness = false

[[test]]
name = "invalid"
harness = false

[[test]]
name = "dangling"
harness = false
