[package]
name = "crates-toml"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { workspace = true }
bumpalo = { workspace = true }
memchr = "2.7.2"

[dev-dependencies]
pretty_assertions = "1.4.0"
